### ISSUE TITLE
关闭主窗口后，会需要较长时间才会结束game()

### ISSUE THREAD

**Issue by NPCTheSBest** [kongkongmao/FNAQ#2]
可能是我的jdk问题。。。
@jacky8399 你来试一下
![233](https://cloud.githubusercontent.com/assets/12973181/14772744/83bf2d9c-0a56-11e6-91f9-2d360fcc1e43.jpg)

**Comment by NPCTheSBest** [comment]
@jacky8399

**Comment by jacky8399** [comment]
最近好忙...qwq
